### ISSUE TITLE
Manual Install Error - Define a 'type' Attribute

### ISSUE THREAD

**Issue by Dinornis** [backdrop-contrib/scheduler#8]
Steps to reproduce:
1. Download Scheduler from GitHub https://github.com/laryn/scheduler/
2. Go to `/admin/modules/install` and select `Manual installation`
3. Expand `Upload a Module`, choose downloaded file and click the `INSTALL` button

Receive Error:
`The info file (temporary://update-extraction-74787aed/scheduler-1.x-1.x/tests/modules/scheduler_test.info) does not define a 'type' attribute.`

Manually placing the Scheduler folder into the `/modules` directory then navigating to `/admin/modules` and enabling the module from there works okay.

**Comment by laryn** [comment]
Fixed.

**Comment by Dinornis** [comment]
Hi @laryn, I downloaded the latest branch cleared all caches and still getting the define type error:

![type-attribute](https://user-images.githubusercontent.com/24782789/30982974-82634fe8-a4e5-11e7-8ba2-cafa00be9aec.png)
Clean install of Backdrop 1.8

**Comment by laryn** [comment]
Very strange. Do you see the `type = module` line in your `scheduler.info` file?

**Comment by laryn** [comment]
Oh, I see the test submodule is what is giving you the error. I haven't worked on that yet. But at a minimum I can add that line in the .info file. :)

**Comment by laryn** [comment]
@Dinornis I added a new commit, can you try again? Thanks for the help!

**Comment by Dinornis** [comment]
Well done, the new commit fixes this issue.
